name: Trigger auto deployment for container-app-fr7u7kqk5nmbq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-fr7u7kqk5nmbq-AutoDeployTrigger-8d3cd0d2-c96f-468f-a940-2d4b5b58c71e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPFR7U7KQK5NMBQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPFR7U7KQK5NMBQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPFR7U7KQK5NMBQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPFR7U7KQK5NMBQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPFR7U7KQK5NMBQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-fr7u7kqk5nmbq
          resourceGroup: appspacesfastapibf02af17
          imageToBuild: default/container-app-fr7u7kqk5nmbq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


